"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class comment_t(object):
    __slots__ = ["utime", "comment"]

    def __init__(self):
        self.utime = 0
        self.comment = ""

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(comment_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __comment_encoded = self.comment.encode('utf-8')
        buf.write(struct.pack('>I', len(__comment_encoded)+1))
        buf.write(__comment_encoded)
        buf.write("\0")

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != comment_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return comment_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = comment_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __comment_len = struct.unpack('>I', buf.read(4))[0]
        self.comment = buf.read(__comment_len)[:-1].decode('utf-8')
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if comment_t in parents: return 0
        newparents = parents + [comment_t]
        tmphash = (0xb11fcf37712d1e76) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if comment_t._packed_fingerprint is None:
            comment_t._packed_fingerprint = struct.pack(">Q", comment_t._get_hash_recursive([]))
        return comment_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

