"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class waypoint_id_t(object):
    __slots__ = ["segment", "lane", "point"]

    def __init__(self):
        self.segment = 0
        self.lane = 0
        self.point = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(waypoint_id_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">hhh", self.segment, self.lane, self.point))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != waypoint_id_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return waypoint_id_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = waypoint_id_t()
        self.segment, self.lane, self.point = struct.unpack(">hhh", buf.read(6))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if waypoint_id_t in parents: return 0
        newparents = parents + [waypoint_id_t]
        tmphash = (0x1dcb0fc3c12bf92) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if waypoint_id_t._packed_fingerprint is None:
            waypoint_id_t._packed_fingerprint = struct.pack(">Q", waypoint_id_t._get_hash_recursive([]))
        return waypoint_id_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

