"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class waypoint_t(object):
    __slots__ = ["utime", "id", "x", "y"]

    def __init__(self):
        self.utime = 0
        self.id = 0
        self.x = 0
        self.y = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(waypoint_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qidd", self.utime, self.id, self.x, self.y))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != waypoint_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return waypoint_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = waypoint_t()
        self.utime, self.id, self.x, self.y = struct.unpack(">qidd", buf.read(28))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if waypoint_t in parents: return 0
        newparents = parents + [waypoint_t]
        tmphash = (0x23d9c6386446c69f) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if waypoint_t._packed_fingerprint is None:
            waypoint_t._packed_fingerprint = struct.pack(">Q", waypoint_t._get_hash_recursive([]))
        return waypoint_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

