"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

import waypoint_t

class waypoint_list_t(object):
    __slots__ = ["utime", "numWaypoints", "waypoints"]

    def __init__(self):
        self.utime = 0
        self.numWaypoints = 0
        self.waypoints = []

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(waypoint_list_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.numWaypoints))
        for i0 in range(self.numWaypoints):
            self.waypoints[i0]._encode_one(buf)

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != waypoint_list_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return waypoint_list_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = waypoint_list_t()
        self.utime, self.numWaypoints = struct.unpack(">qi", buf.read(12))
        self.waypoints = []
        for i0 in range(self.numWaypoints):
            self.waypoints.append(waypoint_t.waypoint_t._decode_one(buf))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if waypoint_list_t in parents: return 0
        newparents = parents + [waypoint_list_t]
        tmphash = (0x7e2a1d09f1394d78+ waypoint_t.waypoint_t._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if waypoint_list_t._packed_fingerprint is None:
            waypoint_list_t._packed_fingerprint = struct.pack(">Q", waypoint_list_t._get_hash_recursive([]))
        return waypoint_list_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

