# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/voom/gui/recorder.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1039, 955)
        MainWindow.setMinimumSize(QtCore.QSize(0, 955))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.playButton = QtGui.QPushButton(self.frame)
        self.playButton.setObjectName(_fromUtf8("playButton"))
        self.horizontalLayout_3.addWidget(self.playButton)
        self.stopButton = QtGui.QPushButton(self.frame)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_3.addWidget(self.stopButton)
        self.recordButton = QtGui.QPushButton(self.frame)
        self.recordButton.setObjectName(_fromUtf8("recordButton"))
        self.horizontalLayout_3.addWidget(self.recordButton)
        self.clearButton = QtGui.QPushButton(self.frame)
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.horizontalLayout_3.addWidget(self.clearButton)
        self.timeLabel = QtGui.QLabel(self.frame)
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        self.horizontalLayout_3.addWidget(self.timeLabel)
        self.gridLayout.addWidget(self.frame, 3, 0, 1, 1)
        self.agentTable = QtGui.QTableView(self.centralwidget)
        self.agentTable.setMaximumSize(QtCore.QSize(16777215, 100))
        self.agentTable.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.agentTable.setObjectName(_fromUtf8("agentTable"))
        self.gridLayout.addWidget(self.agentTable, 4, 0, 1, 1)
        self.commandFrame = QtGui.QFrame(self.centralwidget)
        self.commandFrame.setMinimumSize(QtCore.QSize(0, 50))
        self.commandFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.commandFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.commandFrame.setObjectName(_fromUtf8("commandFrame"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.commandFrame)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.commandLabel = QtGui.QLabel(self.commandFrame)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.commandLabel.setFont(font)
        self.commandLabel.setObjectName(_fromUtf8("commandLabel"))
        self.horizontalLayout_2.addWidget(self.commandLabel)
        self.gridLayout.addWidget(self.commandFrame, 2, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.newAgentButton = QtGui.QPushButton(self.frame_2)
        self.newAgentButton.setObjectName(_fromUtf8("newAgentButton"))
        self.gridLayout_2.addWidget(self.newAgentButton, 0, 0, 1, 1)
        self.removeAgentButton = QtGui.QPushButton(self.frame_2)
        self.removeAgentButton.setObjectName(_fromUtf8("removeAgentButton"))
        self.gridLayout_2.addWidget(self.removeAgentButton, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_2, 6, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.centralwidget)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.placeAgentButton = QtGui.QPushButton(self.frame_3)
        self.placeAgentButton.setObjectName(_fromUtf8("placeAgentButton"))
        self.gridLayout_3.addWidget(self.placeAgentButton, 0, 0, 1, 1)
        self.captureAgentGeomButton = QtGui.QPushButton(self.frame_3)
        self.captureAgentGeomButton.setObjectName(_fromUtf8("captureAgentGeomButton"))
        self.gridLayout_3.addWidget(self.captureAgentGeomButton, 1, 0, 1, 1)
        self.clearAgentGeomButton = QtGui.QPushButton(self.frame_3)
        self.clearAgentGeomButton.setObjectName(_fromUtf8("clearAgentGeomButton"))
        self.gridLayout_3.addWidget(self.clearAgentGeomButton, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_3, 4, 2, 1, 1)
        self.timelineFrame = QtGui.QFrame(self.centralwidget)
        self.timelineFrame.setMinimumSize(QtCore.QSize(0, 150))
        self.timelineFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.timelineFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.timelineFrame.setObjectName(_fromUtf8("timelineFrame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.timelineFrame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout.addWidget(self.timelineFrame, 1, 0, 1, 3)
        self.pathTable = QtGui.QTableView(self.centralwidget)
        self.pathTable.setMaximumSize(QtCore.QSize(16777215, 100))
        self.pathTable.setObjectName(_fromUtf8("pathTable"))
        self.gridLayout.addWidget(self.pathTable, 4, 1, 1, 1)
        self.showFullPathBox = QtGui.QCheckBox(self.centralwidget)
        self.showFullPathBox.setObjectName(_fromUtf8("showFullPathBox"))
        self.gridLayout.addWidget(self.showFullPathBox, 3, 1, 1, 1)
        self.canvasFrame = QtGui.QFrame(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.canvasFrame.sizePolicy().hasHeightForWidth())
        self.canvasFrame.setSizePolicy(sizePolicy)
        self.canvasFrame.setMinimumSize(QtCore.QSize(640, 480))
        self.canvasFrame.setFrameShape(QtGui.QFrame.NoFrame)
        self.canvasFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.canvasFrame.setObjectName(_fromUtf8("canvasFrame"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.canvasFrame)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout.addWidget(self.canvasFrame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1039, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuActions = QtGui.QMenu(self.menubar)
        self.menuActions.setObjectName(_fromUtf8("menuActions"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(MainWindow)
        self.actionNew.setObjectName(_fromUtf8("actionNew"))
        self.actionDisplayPrimitives = QtGui.QAction(MainWindow)
        self.actionDisplayPrimitives.setObjectName(_fromUtf8("actionDisplayPrimitives"))
        self.actionClassify = QtGui.QAction(MainWindow)
        self.actionClassify.setObjectName(_fromUtf8("actionClassify"))
        self.actionSave = QtGui.QAction(MainWindow)
        self.actionSave.setObjectName(_fromUtf8("actionSave"))
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionSave)
        self.menuActions.addAction(self.actionDisplayPrimitives)
        self.menuActions.addAction(self.actionClassify)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuActions.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.playButton.setText(_translate("MainWindow", "Play", None))
        self.stopButton.setText(_translate("MainWindow", "Stop", None))
        self.recordButton.setText(_translate("MainWindow", "Record", None))
        self.clearButton.setText(_translate("MainWindow", "Clear", None))
        self.timeLabel.setText(_translate("MainWindow", "00:00:00", None))
        self.commandLabel.setText(_translate("MainWindow", "Command:", None))
        self.newAgentButton.setText(_translate("MainWindow", "New Agent", None))
        self.removeAgentButton.setText(_translate("MainWindow", "Remove Agent", None))
        self.placeAgentButton.setText(_translate("MainWindow", "Place Agent", None))
        self.captureAgentGeomButton.setText(_translate("MainWindow", "Capture Agent Geom", None))
        self.clearAgentGeomButton.setText(_translate("MainWindow", "Clear Agent Geom", None))
        self.showFullPathBox.setText(_translate("MainWindow", "Show Full Path", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuActions.setTitle(_translate("MainWindow", "Actions", None))
        self.actionNew.setText(_translate("MainWindow", "New", None))
        self.actionDisplayPrimitives.setText(_translate("MainWindow", "Display Primitives", None))
        self.actionDisplayPrimitives.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.actionClassify.setText(_translate("MainWindow", "Classify", None))
        self.actionClassify.setShortcut(_translate("MainWindow", "Ctrl+C", None))
        self.actionSave.setText(_translate("MainWindow", "Save", None))

