here=File.dirname(__FILE__)
$tklib_home=File.expand_path("#{here}/../..")
require "#{$tklib_home}/rakefile.rb"

$CFLAGS = "-c -pipe -Wall -W   -DQT_SHARED -DQT_NO_DEBUG -DQT_THREAD_SUPPORT  -fPIC -fpic"

desc "Build everything."
lib = "c/libgsl_utilities.so"
swig_lib = "swig/_gsl_utilities.so"
ldflags = "--enable-shared -lgsl -lgslcblas -fPIC"




make_o_targets(:build_c, FileList["c/**/*.c"], ".c", "-Wall -fPIC")
make_copy_targets(:build_c, FileList["c/**/*.h"], $include_build_dir)

make_lib_targets(:build_c, lib, FileList["c/*.c"], ldflags, $lib_build_dir)

make_swig_targets(["swig/gsl_utilities.i"], 
                  FileList["c/*.h"],
                  "swig/_gsl_utilities.so", 
                  "-Ic", "-lgsl_utilities")


task :all => [:build_c, :build_swig]



task :clean do
  mkdir_p($include_build_dir)
  mkdir_p($lib_build_dir)
  mkdir_p($pbd)
  sh "rm -f c/*.o"
  sh "rm -f c/*.so"
  sh "rm -f swig/*.o"
  sh "rm -f swig/*.so"
  sh "rm -f swig/*.cxx"
  sh "rm -f swig/*.py"
end
