"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

import cStringIO as StringIO
import struct

class speech_command_t(object):
    __slots__ = ["utime", "command", "uid"]

    def __init__(self):
        self.utime = 0
        self.command = ""
        self.uid = 0

    def encode(self):
        buf = StringIO.StringIO()
        buf.write(speech_command_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        __command_encoded = self.command.encode('utf-8')
        buf.write(struct.pack('>I', len(__command_encoded)+1))
        buf.write(__command_encoded)
        buf.write("\0")
        buf.write(struct.pack(">i", self.uid))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = StringIO.StringIO(data)
        if buf.read(8) != speech_command_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return speech_command_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = speech_command_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        __command_len = struct.unpack('>I', buf.read(4))[0]
        self.command = buf.read(__command_len)[:-1].decode('utf-8')
        self.uid = struct.unpack(">i", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if speech_command_t in parents: return 0
        tmphash = (0x4c54a1fc3850882c) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff 
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None
    
    def _get_packed_fingerprint():
        if speech_command_t._packed_fingerprint is None:
            speech_command_t._packed_fingerprint = struct.pack(">Q", speech_command_t._get_hash_recursive([]))
        return speech_command_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

